version: '3'

services:
  node-service:
    build: ./server
    command: yarn start
    ports:
      - 9001:9001
    environment:
      - NODE_ENV=staging
  nginx-service:
    build: ./client
    volumes:
      - ./client/build:/var/www
    ports:
      - 80:80